#############################
# Xups for Hexo 主题配置文件
# Jelon
# http://jelon.top
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  about:
    name: 归档
    link: /archives/
    icon: icon-lab
  comment:
    name: 留言
    link: /comment/
    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: /favicon.ico

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe id="myWeibo" width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=2376003112&verifier=796ea597&dpc=1"></iframe>

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: true
  owner: icanfly
  repo: blog_comments
  client_id: 9d8f7a953f32b2942597
  client_secret: efbc1217c60b17a9ceae6b2bbc6885dc17c51ac7

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: false
  list:
    1:
      name: Haoren博客
      title: 网络安全博客
      link: http://blog.sina.com.cn/u/1825875765
    2:
      name: Maxwell博客
      title: 技术博客
      link: http://blog.csdn.net/yeweiouyang
    3:
      name: 朱旋个人博客
      title: 技术博客
      link: http://xuanzh.cc/

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/icanfly
      last:
        name: Hosted by Coding Pages
        link: https://pages.coding.me
    sub:
      sinaweibo:
        name: 参与开源
        link: /participate
      qqweibo:
        name: 关于我
        link: /about
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: 分布式, 架构, 后端技术
  description: LP's Notes

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:
